version: '3.0'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT}:4000"
    networks:
      - proxy
    volumes:
      - ./:/usr/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres-db:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${DB_PORT}:5432"
    networks:
      - proxy
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/var/lib/postgresql/data/logs
  
networks:
  proxy:
    driver: bridge
