version: '3.0'

networks:
  user-bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.1.1


services:
  backend:
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT}:4000"
    networks:
      user-bridge:
        ipv4_address: 10.5.1.3
    volumes:
      - ./src:/usr/app/src
    env_file:
      - .env
    depends_on:
      - postgres

  postgres-db:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${DB_PORT}:5432"
    networks:
      user-bridge:
        ipv4_address: 10.5.1.2
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/var/lib/postgresql/data/logs
